// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1300","screenHeight":"740","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Chimaki_AvgMenuBase","status":false,"description":"AVG基本模式介面","parameters":{"ScreenWidth":"1024","ScreenHeight":"624","---------------":"","MenuSwitch":"1","SaveButtonSwitch":"2","SaveButtonImg":"save;100;100","SaveButtonPos":"0;0","LoadButtonSwitch":"3","LoadButtonImg":"load;100;100","LoadButtonPos":"0;0","SystemButtonSwitch":"4","SystemButtonImg":"system;100;100","SystemButtonPos":"0;0","ItemButtonSwitch":"6","ItemButtonImg":"system;100;100","ItemButtonPos":"0;0","ForSystemVar":"8","ForSystemVar2":"","ChoiceWinonwSwitch":"5\r"}},
{"name":"AXY_TitleMenu","status":true,"description":"v1.00 Display Multiple Menu in Title Screen.","parameters":{"DisplayJumpToMap":"false","JumpToMapText":"JumpToMap","JumpToMapId":"1","JumpToMapSwitchId":"0","DisplayExit":"true","ExitText":"Exit","MaxCols":"5","WindowWidth":"840","X":"(Graphics.boxWidth - this.width) / 2","Y":"Graphics.boxHeight - this.height - 96","WindowSkin":"Window","Align":"center","TextColor":"yellow"}},
{"name":"MOG_TitleSplashScreen","status":false,"description":"(v1.0) 标题 - 启动画面","parameters":{"画面持续时间":"6","淡入淡出速度":"10","是否初始全屏":"false","---播放的画面---":"","画面-1":"title01","画面-2":"title02","画面-3":"title03","画面-4":"title04","画面-5":"title05","画面-6":"title06","画面-7":"","画面-8":"","画面-9":"","画面-10":""}},
{"name":"MOG_TitleBackground","status":false,"description":"(v1.1) 标题 - 活动背景","parameters":{"速度-前景画 X":"1","速度-前景画 Y":"0","速度-背景画 X":"0","速度-背景画 Y":"0"}},
{"name":"myTitle","status":true,"description":"","parameters":{}}
];
